name: Python Unit Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # AQUÍ ES DONDE LE DAMOS LAS HERRAMIENTAS AL ROBOT
        pip install numpy pandas seaborn matplotlib pytest 

    - name: Run Tests with Pytest
      run: |
        # Esto le dice que busque 'app.py' en la raíz
        export PYTHONPATH=$PYTHONPATH:. 
        pytest